function features = initialize_nan_features()
%INITIALIZE_NAN_FEATURES  Initialize feature struct with NaN values.
    nan_fields = {'energy', 'uniformity', 'entropy', 'kurtosis', 'skewness', ...
        'p10', 'p90', 'iqr', 'mad', 'rmad', ...
        'glcm_contrast', 'glcm_correlation', 'glcm_energy', 'glcm_homogeneity', ...
        'glrlm_sre', 'glrlm_lre', 'glrlm_gln', 'glrlm_rln', 'glrlm_rp', ...
        'shape_volume', 'shape_surface_area', 'shape_sphericity', ...
        'shape_elongation', 'shape_compactness'};

    features = struct();
    for fi = 1:numel(nan_fields)
        features.(nan_fields{fi}) = NaN;
    end
end
