function run_metrics_longitudinal_step(session, baseline_results)
    fprintf('⚙️ [5.2/5] [%s] Running metrics_longitudinal...\n', session.current_name);
    metrics_longitudinal(baseline_results.ADC_abs, baseline_results.D_abs, baseline_results.f_abs, ...
        baseline_results.Dstar_abs, baseline_results.ADC_pct, baseline_results.D_pct, ...
        baseline_results.f_delta, baseline_results.Dstar_pct, ...
        baseline_results.nTp, baseline_results.dtype_label, ...
        session.config_struct.output_folder, baseline_results.m_lf);
    write_sentinel_file(session.config_struct.output_folder, 'metrics_longitudinal_results', ...
        'Longitudinal metrics generated successfully.', session.current_name);
    fprintf('      ✅ Done.\n');
end
