function run_metrics_stats_comparisons_step(session, baseline_results)
    fprintf('⚙️ [5.4a/5] [%s] Running metrics_stats_comparisons...\n', session.current_name);
    config_struct = session.config_struct;
    metrics_stats_comparisons(baseline_results.valid_pts, baseline_results.lf_group, ...
        baseline_results.metric_sets, baseline_results.set_names, baseline_results.time_labels, ...
        baseline_results.dtype_label, config_struct.output_folder, config_struct.dataloc, ...
        baseline_results.nTp, baseline_results.ADC_abs, baseline_results.D_abs, ...
        baseline_results.f_abs, baseline_results.Dstar_abs);
    write_sentinel_file(config_struct.output_folder, 'metrics_stats_comparisons_results', ...
        'Stats Comparisons generated successfully.', session.current_name);
    fprintf('      ✅ Done.\n');
end
