function run_metrics_stats_predictive_step(session, baseline_results, dosimetry_results, summary_metrics)
    fprintf('⚙️ [5.4b/5] [%s] Running metrics_stats_predictive...\n', session.current_name);
    config_struct = session.config_struct;
    [~, adc_sd_valid_idx] = ismember(baseline_results.m_id_list, summary_metrics.id_list);
    m_adc_sd = summary_metrics.adc_sd(adc_sd_valid_idx, :, :);

    [risk_scores_all, is_high_risk, times_km, events_km] = metrics_stats_predictive( ...
        baseline_results.valid_pts, baseline_results.lf_group, ...
        baseline_results.dtype_label, config_struct.output_folder, config_struct.dataloc, ...
        baseline_results.nTp, baseline_results.m_gtv_vol, m_adc_sd, ...
        baseline_results.ADC_abs, baseline_results.D_abs, baseline_results.f_abs, baseline_results.Dstar_abs, ...
        baseline_results.ADC_pct, baseline_results.D_pct, baseline_results.f_delta, baseline_results.Dstar_pct, ...
        baseline_results.m_d95_gtvp, baseline_results.m_v50gy_gtvp, ...
        dosimetry_results.d95_adc_sub, dosimetry_results.v50_adc_sub, ...
        dosimetry_results.d95_d_sub, dosimetry_results.v50_d_sub, ...
        dosimetry_results.d95_f_sub, dosimetry_results.v50_f_sub, ...
        dosimetry_results.d95_dstar_sub, dosimetry_results.v50_dstar_sub, ...
        baseline_results.m_id_list, config_struct.dwi_types_to_run, ...
        baseline_results.dl_provenance, baseline_results.time_labels, ...
        baseline_results.m_lf, baseline_results.m_total_time, baseline_results.m_total_follow_up_time, config_struct);

    save(session.predictive_results_file, 'risk_scores_all', 'is_high_risk', 'times_km', 'events_km');

    calculated_results = struct();
    calculated_results.risk_scores_all = risk_scores_all;
    calculated_results.is_high_risk = is_high_risk;
    calculated_results.times_km = times_km;
    calculated_results.events_km = events_km;
    calculated_results.m_lf = baseline_results.m_lf;
    calculated_results.m_id_list = baseline_results.m_id_list;
    save(session.results_file, 'calculated_results');
    fprintf('      💾 Saved calculated_results to %s\n', session.results_file);
    fprintf('      ✅ Done.\n');
end
