function run_metrics_dosimetry_step(session, baseline_results, summary_metrics)
    fprintf('⚙️ [5.3/5] [%s] Running metrics_dosimetry...\n', session.current_name);
    config_struct = session.config_struct;
    if config_struct.run_all_core_methods
        [d95_adc_sub, v50_adc_sub, d95_d_sub, v50_d_sub, d95_f_sub, v50_f_sub, d95_dstar_sub, v50_dstar_sub, per_method_dosimetry, dmean_adc_sub, dmean_d_sub, dmean_f_sub, dmean_dstar_sub] = ...
            metrics_dosimetry(baseline_results.m_id_list, summary_metrics.id_list, baseline_results.nTp, config_struct, ...
                              baseline_results.m_data_vectors_gtvp, summary_metrics.gtv_locations);
    else
        [d95_adc_sub, v50_adc_sub, d95_d_sub, v50_d_sub, d95_f_sub, v50_f_sub, d95_dstar_sub, v50_dstar_sub, ~, dmean_adc_sub, dmean_d_sub, dmean_f_sub, dmean_dstar_sub] = ...
            metrics_dosimetry(baseline_results.m_id_list, summary_metrics.id_list, baseline_results.nTp, config_struct, ...
                              baseline_results.m_data_vectors_gtvp, summary_metrics.gtv_locations);
        per_method_dosimetry = struct();
    end
    save(session.dosimetry_results_file, 'd95_adc_sub', 'v50_adc_sub', 'd95_d_sub', 'v50_d_sub', ...
        'd95_f_sub', 'v50_f_sub', 'd95_dstar_sub', 'v50_dstar_sub', 'per_method_dosimetry', ...
        'dmean_adc_sub', 'dmean_d_sub', 'dmean_f_sub', 'dmean_dstar_sub');
    fprintf('      ✅ Done.\n');
end
