classdef test_convert_dicom < matlab.unittest.TestCase
    % TEST_CONVERT_DICOM Unit tests for the convert_dicom function

    properties
        TestDir
        DicomLoc
        OutLoc
        MockScript
    end

    methods (TestMethodSetup)
        function createTempDirs(testCase)
            % Create a temporary directory for the tests
            testCase.TestDir = tempname;
            mkdir(testCase.TestDir);

            testCase.DicomLoc = fullfile(testCase.TestDir, 'dicom');
            mkdir(testCase.DicomLoc);

            testCase.OutLoc = fullfile(testCase.TestDir, 'out');
            mkdir(testCase.OutLoc);

            % Create a mock dcm2niix script based on OS
            if ispc
                testCase.MockScript = fullfile(testCase.TestDir, 'mock_dcm2niix.bat');
                % A batch script that we can overwrite dynamically
                fid = fopen(testCase.MockScript, 'w');
                fprintf(fid, '@echo off\nexit /b 0\n');
                fclose(fid);
            else
                testCase.MockScript = fullfile(testCase.TestDir, 'mock_dcm2niix.sh');
                fid = fopen(testCase.MockScript, 'w');
                fprintf(fid, '#!/bin/bash\nexit 0\n');
                fclose(fid);
                system(['chmod +x ' testCase.MockScript]);
            end
        end
    end

    methods (TestMethodTeardown)
        function removeTempDirs(testCase)
            % Clean up temporary directory
            if exist(testCase.TestDir, 'dir')
                rmdir(testCase.TestDir, 's');
            end
        end
    end

    methods (Test)

        function test_success_three_files(testCase)
            % Test when exactly 3 files + 1 dir entry = 4 delta generated by the system command
            scanID = 'scan_001';
            fx_id = 'fx_test';

            % Update mock script to generate 4 files (which simulates 3 files + dir delta) in OutLoc
            fid = fopen(testCase.MockScript, 'w');
            if ispc
                fprintf(fid, '@echo off\n');
                fprintf(fid, 'echo dummy > "%s\\file1.txt"\n', testCase.OutLoc);
                fprintf(fid, 'echo dummy > "%s\\file2.txt"\n', testCase.OutLoc);
                fprintf(fid, 'echo dummy > "%s\\file3.txt"\n', testCase.OutLoc);
                fprintf(fid, 'echo dummy > "%s\\file4.txt"\n', testCase.OutLoc);
            else
                fprintf(fid, '#!/bin/bash\n');
                fprintf(fid, 'touch "%s/file1.txt"\n', testCase.OutLoc);
                fprintf(fid, 'touch "%s/file2.txt"\n', testCase.OutLoc);
                fprintf(fid, 'touch "%s/file3.txt"\n', testCase.OutLoc);
                fprintf(fid, 'touch "%s/file4.txt"\n', testCase.OutLoc);
            end
            fclose(fid);
            if ~ispc
                system(['chmod +x ' testCase.MockScript]);
            end

            bad_dwi_found = convert_dicom(testCase.DicomLoc, testCase.OutLoc, scanID, testCase.MockScript, fx_id);

            testCase.verifyEqual(bad_dwi_found, 0, 'Should return 0 when dir length increases by exactly 4.');
        end

        function test_failure_wrong_files(testCase)
            % Test when not exactly 4 files delta are generated
            scanID = 'scan_002';
            fx_id = 'fx_test';

            % Update mock script to generate only 3 files delta in OutLoc
            fid = fopen(testCase.MockScript, 'w');
            if ispc
                fprintf(fid, '@echo off\n');
                fprintf(fid, 'echo dummy > "%s\\file1.txt"\n', testCase.OutLoc);
                fprintf(fid, 'echo dummy > "%s\\file2.txt"\n', testCase.OutLoc);
                fprintf(fid, 'echo dummy > "%s\\file3.txt"\n', testCase.OutLoc);
            else
                fprintf(fid, '#!/bin/bash\n');
                fprintf(fid, 'touch "%s/file1.txt"\n', testCase.OutLoc);
                fprintf(fid, 'touch "%s/file2.txt"\n', testCase.OutLoc);
                fprintf(fid, 'touch "%s/file3.txt"\n', testCase.OutLoc);
            end
            fclose(fid);
            if ~ispc
                system(['chmod +x ' testCase.MockScript]);
            end

            bad_dwi_found = convert_dicom(testCase.DicomLoc, testCase.OutLoc, scanID, testCase.MockScript, fx_id);

            testCase.verifyEqual(bad_dwi_found, 1, 'Should return 1 when dir length increases by 3 instead of 4.');
        end

        function test_skip_existing_file(testCase)
            % Test when the primary .nii.gz file already exists
            scanID = 'scan_003';
            fx_id = 'fx_test';

            % Create the output file beforehand
            fid = fopen(fullfile(testCase.OutLoc, [scanID '.nii.gz']), 'w');
            fprintf(fid, 'dummy content');
            fclose(fid);

            % Update mock script to generate 10 files (which would fail if executed)
            fid = fopen(testCase.MockScript, 'w');
            if ispc
                fprintf(fid, '@echo off\n');
                for i = 1:10
                    fprintf(fid, 'echo dummy > "%s\\file%%d.txt"\n', testCase.OutLoc, i);
                end
            else
                fprintf(fid, '#!/bin/bash\n');
                for i = 1:10
                    fprintf(fid, 'touch "%s/file%d.txt"\n', testCase.OutLoc, i);
                end
            end
            fclose(fid);
            if ~ispc
                system(['chmod +x ' testCase.MockScript]);
            end

            bad_dwi_found = convert_dicom(testCase.DicomLoc, testCase.OutLoc, scanID, testCase.MockScript, fx_id);

            % Should return 0 and skip execution because file exists
            testCase.verifyEqual(bad_dwi_found, 0, 'Should return 0 and skip generation if file already exists.');
        end

    end

end
