function [n_sig, sig_data_selected, sig_names, sig_is_abs, ...
    sig_is_pct_imaging, sig_disp_names, sig_units, sig_col_idx, ...
    sig_abs_data, sig_pct_data] = build_predictive_feature_metadata( ...
        selected_indices, target_fx, ...
        ADC_abs_valid, D_abs_valid, f_abs_valid, Dstar_abs_valid, ...
        ADC_pct_valid, D_pct_valid, f_delta_valid, Dstar_pct_valid, ...
        m_d95_gtvp_valid, m_v50gy_gtvp_valid, ...
        d95_adc_sub_valid, v50_adc_sub_valid, d95_d_sub_valid, v50_d_sub_valid, ...
        d95_f_sub_valid, v50_f_sub_valid, d95_dstar_sub_valid, v50_dstar_sub_valid)
% BUILD_PREDICTIVE_FEATURE_METADATA — Feature metadata assembly for
% metrics_stats_predictive diagnostics.
%
% Extracted verbatim from metrics_stats_predictive.m ("Build feature
% metadata for diagnostics" block) to keep that file under the per-file
% line budget.  Given the elastic-net-selected feature indices and the
% pre-indexed (valid_pts subset) parameter arrays, this builds the 22-entry
% candidate feature catalog (data / names / abs-flag / display name / units)
% and then maps the selected indices into the per-significant-feature arrays
% (sig_*) consumed by plot_predictive_diagnostics.
%
% Inputs:
%   selected_indices  - elastic-net-selected feature column indices (1..22)
%   target_fx         - target fraction (timepoint) index
%   *_valid           - parameter arrays already subset to valid patients
%
% Outputs:
%   n_sig             - number of selected features
%   sig_data_selected - {1 x n_sig} selected feature data arrays
%   sig_names         - {1 x n_sig} short feature names
%   sig_is_abs        - 1 x n_sig logical: feature is an absolute value
%   sig_is_pct_imaging- 1 x n_sig logical: feature is a percent-change imaging metric
%   sig_disp_names    - {1 x n_sig} display names (LaTeX)
%   sig_units         - {1 x n_sig} units strings
%   sig_col_idx       - 1 x n_sig column index (1 for baseline, target_fx otherwise)
%   sig_abs_data      - {1 x n_sig} paired absolute-value data arrays
%   sig_pct_data      - {1 x n_sig} paired percent-change data arrays

    all_feat_data  = {ADC_abs_valid,       D_abs_valid,       f_abs_valid,       Dstar_abs_valid, ...
                      ADC_abs_valid,       D_abs_valid,       f_abs_valid,       Dstar_abs_valid, ...
                      ADC_pct_valid,       D_pct_valid,       f_delta_valid,       Dstar_pct_valid, ...
                      m_d95_gtvp_valid,    m_v50gy_gtvp_valid, ...
                      d95_adc_sub_valid,   v50_adc_sub_valid, ...
                      d95_d_sub_valid,     v50_d_sub_valid, ...
                      d95_f_sub_valid,     v50_f_sub_valid, ...
                      d95_dstar_sub_valid, v50_dstar_sub_valid};

    all_feat_names = {'ADC BL',      'D BL',      'f BL',      'D* BL', ...
                      'ADC',         'D',         'f',         'D*', ...
                      'ADC',         'D',         'f',         'D*', ...
                      'D95 GTVp',    'V50 GTVp', ...
                      'D95 Sub(ADC)','V50 Sub(ADC)', ...
                      'D95 Sub(D)',  'V50 Sub(D)', ...
                      'D95 Sub(f)',  'V50 Sub(f)', ...
                      'D95 Sub(D*)', 'V50 Sub(D*)'};

    all_feat_is_abs = [true          true         true         true  ...
                       true          true         true         true  ...
                       false         false        false        false ...
                       true          false        true         false ...
                       true          false        true         false ...
                       true          false];

    all_feat_disp  = {'BL ADC',      'BL D',      'BL f',      'BL D*', ...
                      'Abs ADC',     'Abs D',     'Abs f',     'Abs D*', ...
                      '\Delta ADC',  '\Delta D',  '\Delta f',  '\Delta D*', ...
                      'D95 GTVp',    'V50 GTVp', ...
                      'D95 Sub(ADC)','V50 Sub(ADC)', ...
                      'D95 Sub(D)',  'V50 Sub(D)', ...
                      'D95 Sub(f)',  'V50 Sub(f)', ...
                      'D95 Sub(D*)', 'V50 Sub(D*)'};

    all_feat_units = {'mm^2/s',      'mm^2/s',    'Fraction',  'mm^2/s', ...
                      'mm^2/s',      'mm^2/s',    'Fraction',  'mm^2/s', ...
                      '%',           '%',         'Fraction',  '%', ...
                      'Gy',          '%', ...
                      'Gy',          '%', ...
                      'Gy',          '%', ...
                      'Gy',          '%'};

    n_sig = length(selected_indices);

    sig_data_selected = cell(1, n_sig);
    sig_abs_data      = cell(1, n_sig);
    sig_pct_data      = cell(1, n_sig);
    sig_names         = cell(1, n_sig);
    sig_is_abs        = false(1, n_sig);
    sig_is_pct_imaging = false(1, n_sig);
    sig_disp_names    = cell(1, n_sig);
    sig_units         = cell(1, n_sig);
    sig_col_idx       = zeros(1, n_sig);

    for si = 1:n_sig
        fi = selected_indices(si);
        sig_data_selected{si} = all_feat_data{fi};
        sig_names{si}         = all_feat_names{fi};
        sig_is_abs(si)        = all_feat_is_abs(fi);
        sig_is_pct_imaging(si) = (fi >= 9 && fi <= 12);
        sig_disp_names{si}    = all_feat_disp{fi};
        sig_units{si}         = all_feat_units{fi};
        if fi <= 4
            sig_col_idx(si) = 1;
        else
            sig_col_idx(si) = target_fx;
        end

        if fi <= 4
            sig_abs_data{si} = all_feat_data{fi};
            sig_pct_data{si} = all_feat_data{min(fi + 8, numel(all_feat_data))};
        elseif fi >= 5 && fi <= 8
            sig_abs_data{si} = all_feat_data{fi};
            sig_pct_data{si} = all_feat_data{fi + 4};
        elseif fi >= 9 && fi <= 12
            sig_abs_data{si} = all_feat_data{fi - 4};
            sig_pct_data{si} = all_feat_data{fi};
        else
            sig_abs_data{si} = all_feat_data{fi};
            sig_pct_data{si} = all_feat_data{fi};
        end
    end
end
