"""Report sections: metadata group."""

from __future__ import annotations

from report_formatters import (  # type: ignore
    NAV_GROUPS,
    _esc,
    _figure_caption,
    _h2,
    _table_caption,
    get_numbering,
)


def _section_cover_page(timestamp: str, dwi_types_present: list[str], n_graphs: int) -> list[str]:
    """Build a PDF cover page (hidden on screen, first page in print).

    Parameters
    ----------
    timestamp : str
        Run timestamp string extracted from the folder name.
    dwi_types_present : list[str]
        DWI processing types present in this run.
    n_graphs : int
        Number of graphs analysed by the vision pipeline (0 if none).

    Returns
    -------
    list[str]
        HTML chunks for the cover page element.
    """
    h: list[str] = []
    h.append('<div class="cover-page">')
    h.append(
        '<h1>DWI Biomarker Analysis Report<br>'
        '<span style="font-size:0.6em;font-weight:400;color:#555;">'
        "Pancreatic Cancer — Memorial Sloan Kettering Cancer Center"
        "</span></h1>"
    )
    h.append('<div class="cover-rule"></div>')
    h.append('<div class="cover-meta">')
    h.append(f"<div><strong>Run timestamp:</strong> {_esc(timestamp)}</div>")
    if dwi_types_present:
        h.append(
            f"<div><strong>DWI types:</strong> {_esc(', '.join(dwi_types_present))}</div>"
        )
    if n_graphs:
        h.append(f"<div><strong>Graphs analysed:</strong> {n_graphs}</div>")
    h.append(
        "<div style='margin-top:0.5cm;'>"
        "<em>Generated by the pancData3 analysis pipeline</em>"
        "</div>"
    )
    h.append("</div>")
    h.append("</div>")
    return h


def _part_break(label: str) -> str:
    """Return a print-only part-break divider string.

    On screen this element is ``display:none``.  In print it forces a
    page break and renders the part label as a chapter heading.

    Parameters
    ----------
    label : str
        Part title shown at the top of the new page (e.g. ``"Data"``).

    Returns
    -------
    str
        Single HTML string for the part-break element.
    """
    return f'<div class="part-break">{_esc(label)}</div>'


def _section_print_toc() -> list[str]:
    """Build a Table of Contents section visible on screen and in PDF output.

    Renders all report sections grouped by category, matching the sticky
    navigation bar.  On screen it appears as a two-column box; in print/PDF
    it occupies its own page (``page-break-after: always``).

    Returns
    -------
    list[str]
        HTML chunks for the table of contents section.
    """
    h: list[str] = []
    h.append('<div class="print-toc" id="toc">')
    h.append("<h2>Table of Contents</h2>")
    for group_label, sections in NAV_GROUPS:
        h.append('<div class="print-toc-group">')
        h.append(
            f'<span class="print-toc-group-label">{_esc(group_label)}</span>'
        )
        h.append('<ul class="print-toc-list">')
        for anchor, label in sections:
            h.append(f'<li><a href="#{anchor}">{_esc(label)}</a></li>')
        h.append("</ul>")
        h.append("</div>")
    h.append("</div>")
    return h


def _section_publication_header() -> list[str]:
    """Build a publication metadata block with author/institution placeholders.

    This section provides fill-in-the-blank placeholders for manuscript
    metadata that cannot be auto-generated (author names, affiliations,
    corresponding author, IRB approval number).

    Returns
    -------
    list[str]
        HTML chunks for the publication metadata block.
    """
    h: list[str] = []
    h.append('<div class="pub-meta">')
    h.append("<h4>Manuscript Information</h4>")
    h.append('<p><strong>Title:</strong> <span class="placeholder">'
             "Diffusion-Weighted MRI Biomarkers for Treatment Response "
             "Assessment in Pancreatic Cancer: A Multi-Strategy Analysis"
             "</span></p>")
    h.append('<p><strong>Authors:</strong> <span class="placeholder">'
             "[Author 1, Author 2, ... ]</span></p>")
    h.append('<p><strong>Affiliations:</strong> <span class="placeholder">'
             "Department of Medical Physics, Memorial Sloan Kettering Cancer Center, "
             "New York, NY</span></p>")
    h.append('<p><strong>Corresponding Author:</strong> <span class="placeholder">'
             "[Name, email]</span></p>")
    h.append('<p><strong>IRB Approval:</strong> <span class="placeholder">'
             "[Protocol number]</span></p>")
    h.append("</div>")
    return h



def _section_data_availability() -> list[str]:
    """Build the Data Availability Statement section.

    Returns
    -------
    list[str]
        HTML chunks for the data availability section.
    """
    h: list[str] = []
    h.append(_h2("Data Availability", "data-availability"))
    h.append('<div class="methods-box">')
    h.append(
        "<p>The clinical imaging data supporting this study are subject to "
        "institutional review board (IRB) restrictions and cannot be made "
        "publicly available due to patient privacy requirements under HIPAA. "
        "De-identified summary statistics and analysis code are available "
        "from the corresponding author upon reasonable request.</p>"
    )
    h.append(
        "<p>The analysis pipeline source code (pancData3) is available "
        "under the MIT License. Post-hoc analysis scripts and report "
        "generation tools are included in the repository.</p>"
    )
    h.append("</div>")
    return h



def _section_table_index() -> list[str]:
    """Build a List of Tables section from auto-numbered table captions.

    This section is generated from the :class:`_NumberingContext` which
    tracks all ``_table_caption`` calls during report generation.

    Returns
    -------
    list[str]
        HTML chunks for the list of tables section.
    """
    h: list[str] = []
    numbering = get_numbering()
    if not numbering.table_titles:
        return h

    h.append(_h2("List of Tables", "table-index"))
    h.append('<ol class="toc-list">')
    for num, title in numbering.table_titles:
        h.append(f"<li><strong>Table {num}.</strong> {_esc(title)}</li>")
    h.append("</ol>")

    return h



def _section_figure_index() -> list[str]:
    """Build a List of Figures section from auto-numbered figure captions.

    This section is generated from the :class:`_NumberingContext` which
    tracks all ``_figure_caption`` calls during report generation.

    Returns
    -------
    list[str]
        HTML chunks for the list of figures section.
    """
    h: list[str] = []
    numbering = get_numbering()
    if not numbering.figure_titles:
        return h

    h.append(_h2("List of Figures", "figure-index"))
    h.append('<ol class="toc-list">')
    for num, title in numbering.figure_titles:
        h.append(f"<li><strong>Figure {num}.</strong> {_esc(title)}</li>")
    h.append("</ol>")

    return h


