"""Integration tests for full HTML report generation.

Covers:
- generate_report: end-to-end report generation with mocked data
- Publication-level sections: Methods, Effect Sizes, Multiple Comparisons,
  Model Diagnostics, Limitations, Conclusions
- New section integration (checklist, BibTeX, STROBE, results draft, gallery)
- BibTeX export and JavaScript inclusion
- Data quality: outlier balance, Cox PH direction, correlations context
"""

from __future__ import annotations

from pathlib import Path

import pytest  # type: ignore

from report.generate_report import (  # type: ignore
    generate_report,
    REPORT_JS,
)


# ---------------------------------------------------------------------------
# TestGenerateReport — main integration test class
# ---------------------------------------------------------------------------


class TestGenerateReport:
    """Integration tests for the full Markdown report generation."""

    def test_report_contains_header(self, saved_files_with_graph_csv: Path):
        """Report should contain the formatted run timestamp in the title."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Analysis Report" in report
        # Timestamp is now formatted: "March 1, 2026 at 12:00:00"
        assert "March 1, 2026" in report

    def test_report_contains_dwi_types(self, saved_files_with_graph_csv: Path):
        """All three DWI types should be mentioned somewhere in the report."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Standard" in report
        assert "dnCNN" in report
        assert "IVIMnet" in report

    def test_report_contains_graph_overview(self, saved_files_with_graph_csv: Path):
        """The graph type table should appear."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Graph Type" in report
        assert "box" in report
        assert "line" in report

    def test_report_contains_graph_issues(self, saved_files_with_graph_csv: Path):
        """Graph Issues section should show detected issues from the CSV."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Graph Issues" in report
        assert "Y-axis label partially obscured by legend" in report
        assert "Overlapping legend text" in report

    def test_report_extracts_significant_pvalues(self, saved_files_with_graph_csv: Path):
        """P-values < 0.05 from the graph CSV should appear in the report."""
        report = generate_report(saved_files_with_graph_csv)
        # The fixture has p = 0.003 and p-value = 0.02
        assert "0.003" in report or "0.0030" in report

    def test_report_extracts_correlations(self, saved_files_with_graph_csv: Path):
        """Notable correlations should appear in the report."""
        report = generate_report(saved_files_with_graph_csv)
        # The fixture has r = 0.65
        assert "0.65" in report

    def test_report_appendix_lists_all_graphs(self, saved_files_with_graph_csv: Path):
        report = generate_report(saved_files_with_graph_csv)
        assert "Appendix" in report
        assert "Feature_BoxPlots" in report

    def test_report_footer(self, saved_files_with_graph_csv: Path):
        report = generate_report(saved_files_with_graph_csv)
        assert "Report generated by pancData3" in report

    def test_empty_folder_still_generates(self, saved_files_dir: Path):
        """A folder with no graph CSV and no logs should still produce a report."""
        report = generate_report(saved_files_dir)
        assert "Analysis Report" in report
        assert "No significant findings" in report or "No predictive" in report

    def test_report_with_logs(self, saved_files_with_logs: Path):
        """With log data present, predictive performance should appear."""
        report = generate_report(saved_files_with_logs)
        # The fixture has AUC = 0.781
        assert "0.781" in report or "Predictive" in report

    def test_report_cross_dwi_comparison(self, saved_files_with_graph_csv: Path):
        """Cross-DWI comparison section for Feature_BoxPlots (Standard + dnCNN)."""
        report = generate_report(saved_files_with_graph_csv)
        # Feature_BoxPlots has Standard (increasing) and dnCNN (decreasing) -> DIFFER
        if "Cross-DWI" in report:
            assert "DIFFER" in report or "AGREE" in report

    def test_report_is_valid_html(self, saved_files_with_graph_csv: Path):
        """Basic structural check: headings and tables."""
        report = generate_report(saved_files_with_graph_csv)
        assert "<h2" in report  # at least a few headings
        assert "<table" in report  # at least one table

    def test_report_contains_methods_section(self, saved_files_with_graph_csv: Path):
        """The Methods section should describe statistical methodology."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Statistical Methods" in report
        assert "Wilcoxon" in report
        assert "Benjamini" in report
        assert "Cox" in report

    def test_report_contains_structured_abstract(self, saved_files_with_graph_csv: Path):
        """Executive summary should have structured abstract subsections."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Objective" in report
        assert "Key Results" in report
        assert "Conclusions" in report

    def test_report_contains_limitations(self, saved_files_with_graph_csv: Path):
        """Limitations section should appear in the report."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Limitations" in report
        assert "Single-institution" in report

    def test_report_contains_model_diagnostics(self, saved_files_with_graph_csv: Path):
        """Model diagnostics section should have assumptions listed."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Model Diagnostics" in report
        assert "Proportional hazards" in report

    def test_report_contains_conclusions_section(self, saved_files_with_graph_csv: Path):
        """Conclusions section should appear."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Conclusions" in report
        assert "Future directions" in report

    def test_report_with_logs_has_effect_sizes(self, saved_files_with_logs: Path):
        """With log data, the Effect Size section should report HR effects."""
        report = generate_report(saved_files_with_logs)
        assert "Effect Size" in report

    def test_report_with_logs_has_multiple_comparisons(self, saved_files_with_logs: Path):
        """With log data, the Multiple Comparisons section should appear."""
        report = generate_report(saved_files_with_logs)
        assert "Multiple Comparison" in report
        assert "BH-FDR" in report or "FDR" in report

    def test_report_with_logs_has_diagnostics_detail(self, saved_files_with_logs: Path):
        """With log data, model diagnostics should show data-driven issues."""
        report = generate_report(saved_files_with_logs)
        assert "IPCW" in report or "weight" in report or "Assumptions" in report

    def test_report_with_logs_has_discrimination_table(self, saved_files_with_logs: Path):
        """AUC discrimination interpretation should appear."""
        report = generate_report(saved_files_with_logs)
        # The fixture has AUC = 0.781, which maps to "Acceptable"
        assert "Acceptable" in report or "Discrimination" in report or "discrimination" in report


# ---------------------------------------------------------------------------
# BibTeX export
# ---------------------------------------------------------------------------


class TestBibTeXExport:
    """Verify BibTeX export in references section."""

    def test_report_contains_bibtex(self, saved_files_with_graph_csv: Path):
        """Report includes BibTeX export block."""
        report = generate_report(saved_files_with_graph_csv)
        assert "BibTeX" in report
        assert "@article" in report or "@book" in report

    def test_report_contains_js(self, saved_files_with_graph_csv: Path):
        """Report includes JavaScript for copy-to-clipboard."""
        report = generate_report(saved_files_with_graph_csv)
        assert "copyText" in report

    def test_report_js_constant_exists(self):
        """REPORT_JS constant is a non-empty string."""
        assert isinstance(REPORT_JS, str)
        assert len(REPORT_JS) > 50
        assert "copyText" in REPORT_JS


# ---------------------------------------------------------------------------
# Full integration: new sections in report
# ---------------------------------------------------------------------------


class TestNewSectionsIntegration:
    """Verify new sections appear in the full report."""

    def test_report_has_checklist(self, saved_files_with_graph_csv: Path):
        """Full report includes the reporting checklist section."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Reporting Guideline" in report

    def test_report_has_bibtex_block(self, saved_files_with_graph_csv: Path):
        """Full report includes the BibTeX export."""
        report = generate_report(saved_files_with_graph_csv)
        assert "bibtex-block" in report

    def test_report_has_strobe_reference(self, saved_files_with_graph_csv: Path):
        """Full report includes STROBE and REMARK references."""
        report = generate_report(saved_files_with_graph_csv)
        assert "STROBE" in report
        assert "REMARK" in report

    def test_report_has_results_draft(self, saved_files_with_graph_csv: Path):
        """Full report includes the draft results section."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Draft Results Section" in report

    def test_report_has_figure_gallery(self, saved_files_with_graph_csv: Path):
        """Full report includes figure gallery section (even if empty)."""
        # The gallery renders even with no images (it just returns [])
        report = generate_report(saved_files_with_graph_csv)
        # Gallery may be empty if no images exist, that's fine
        assert report  # report should still generate successfully

    def test_report_has_journal_guide(self, saved_files_with_graph_csv: Path):
        """Full report includes journal submission guidance."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Journal Submission Guidance" in report


# ---------------------------------------------------------------------------
# Data quality outlier balance and bias detection
# ---------------------------------------------------------------------------


class TestDataQualityOutlierBalance:
    """Verify outlier balance and bias detection in the Data Quality section."""

    def test_report_with_logs_shows_balance_column(self, saved_files_with_logs: Path):
        """Data quality outlier table includes a Balance column."""
        report = generate_report(saved_files_with_logs)
        assert "Balance" in report

    def test_report_with_logs_shows_baseline_exclusion(self, saved_files_with_logs: Path):
        """Data quality section shows baseline exclusion info."""
        report = generate_report(saved_files_with_logs)
        # The fixture has baseline exclusion: 6/48 patients
        assert "Baseline Excluded" in report or "baseline" in report.lower()


# ---------------------------------------------------------------------------
# Cox PH direction column
# ---------------------------------------------------------------------------


class TestCoxPHDirectionColumn:
    """Verify the HR direction column in Cox PH tables."""

    def test_report_with_logs_shows_hr_direction(self, saved_files_with_logs: Path):
        """Cox PH table should show Risk/Protective direction."""
        report = generate_report(saved_files_with_logs)
        # The fixture has HR=1.250 (Risk) and HR=0.750 (Protective)
        assert "Direction" in report
        assert "Risk" in report or "Protective" in report

    def test_report_with_logs_shows_discrimination_column(self, saved_files_with_logs: Path):
        """ROC table should include AUC discrimination rating."""
        report = generate_report(saved_files_with_logs)
        assert "Discrimination" in report
        # AUC 0.781 -> Acceptable
        assert "Acceptable" in report


# ---------------------------------------------------------------------------
# Correlations interpretation context
# ---------------------------------------------------------------------------


class TestCorrelationsContext:
    """Verify correlation section has interpretation guidance."""

    def test_report_has_correlation_benchmarks(self, saved_files_with_graph_csv: Path):
        """Correlation section mentions Cohen's strength benchmarks."""
        report = generate_report(saved_files_with_graph_csv)
        if "Correlations" in report:
            assert "Cohen" in report or "strength" in report.lower()
