"""Tests for generate_report.py — Markdown report generation.

Covers:
- _sig_tag: p-value → significance star mapping
- _section: Markdown heading generation
- generate_report: full report generation with mocked data sources
"""

from __future__ import annotations

from pathlib import Path

import pytest

from generate_report import _section, _sig_tag, generate_report


# ---------------------------------------------------------------------------
# _sig_tag
# ---------------------------------------------------------------------------

class TestSigTag:
    """Verify p-value to significance star mapping."""

    def test_three_stars(self):
        """p < 0.001 gets triple stars (highly significant)."""
        assert _sig_tag(0.0001) == "***"
        assert _sig_tag(0.0009) == "***"

    def test_two_stars(self):
        """0.001 <= p < 0.01 gets double stars."""
        assert _sig_tag(0.001) == "**"
        assert _sig_tag(0.005) == "**"
        assert _sig_tag(0.009) == "**"

    def test_one_star(self):
        """0.01 <= p < 0.05 gets a single star."""
        assert _sig_tag(0.01) == "*"
        assert _sig_tag(0.049) == "*"

    def test_not_significant(self):
        """p >= 0.05 gets no star (empty string)."""
        assert _sig_tag(0.05) == ""
        assert _sig_tag(0.5) == ""
        assert _sig_tag(1.0) == ""

    def test_boundary_values(self):
        """Boundary at 0.001, 0.01, 0.05 (exclusive lower bound)."""
        assert _sig_tag(0.001) == "**"   # exactly 0.001 → **
        assert _sig_tag(0.01) == "*"     # exactly 0.01 → *
        assert _sig_tag(0.05) == ""      # exactly 0.05 → not significant


# ---------------------------------------------------------------------------
# _section
# ---------------------------------------------------------------------------

class TestSection:
    """Verify Markdown section header generation."""

    def test_default_h2(self):
        result = _section("My Section")
        assert result == "\n## My Section\n"

    def test_h3(self):
        result = _section("Subsection", level=3)
        assert result == "\n### Subsection\n"

    def test_h1(self):
        result = _section("Title", level=1)
        assert result == "\n# Title\n"


# ---------------------------------------------------------------------------
# generate_report (integration)
# ---------------------------------------------------------------------------

class TestGenerateReport:
    """Integration tests for the full Markdown report generation."""

    def test_report_contains_header(self, saved_files_with_graph_csv: Path):
        """Report should contain the folder timestamp in the title."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Analysis Report" in report
        assert "20260301_120000" in report

    def test_report_contains_dwi_types(self, saved_files_with_graph_csv: Path):
        report = generate_report(saved_files_with_graph_csv)
        assert "Standard" in report
        assert "dnCNN" in report
        assert "IVIMnet" in report

    def test_report_contains_graph_overview(self, saved_files_with_graph_csv: Path):
        """The graph type table should appear."""
        report = generate_report(saved_files_with_graph_csv)
        assert "Graph Type" in report
        assert "box" in report
        assert "line" in report

    def test_report_extracts_significant_pvalues(self, saved_files_with_graph_csv: Path):
        """P-values < 0.05 from the graph CSV should appear in the report."""
        report = generate_report(saved_files_with_graph_csv)
        # The fixture has p = 0.003 and p-value = 0.02
        assert "0.003" in report or "0.0030" in report

    def test_report_extracts_correlations(self, saved_files_with_graph_csv: Path):
        """Notable correlations should appear in the report."""
        report = generate_report(saved_files_with_graph_csv)
        # The fixture has r = 0.65
        assert "0.65" in report

    def test_report_appendix_lists_all_graphs(self, saved_files_with_graph_csv: Path):
        report = generate_report(saved_files_with_graph_csv)
        assert "Appendix" in report
        assert "Feature_BoxPlots" in report

    def test_report_footer(self, saved_files_with_graph_csv: Path):
        report = generate_report(saved_files_with_graph_csv)
        assert "Report generated by pancData3" in report

    def test_empty_folder_still_generates(self, saved_files_dir: Path):
        """A folder with no graph CSV and no logs should still produce a report."""
        report = generate_report(saved_files_dir)
        assert "Analysis Report" in report
        assert "No significant findings" in report or "No predictive" in report

    def test_report_with_logs(self, saved_files_with_logs: Path):
        """With log data present, predictive performance should appear."""
        report = generate_report(saved_files_with_logs)
        # The fixture has AUC = 0.781
        assert "0.781" in report or "Predictive" in report

    def test_report_cross_dwi_comparison(self, saved_files_with_graph_csv: Path):
        """Cross-DWI comparison section for Feature_BoxPlots (Standard + dnCNN)."""
        report = generate_report(saved_files_with_graph_csv)
        # Feature_BoxPlots has Standard (increasing) and dnCNN (decreasing) → DIFFER
        if "Cross-DWI" in report:
            assert "DIFFER" in report or "AGREE" in report

    def test_report_is_valid_markdown(self, saved_files_with_graph_csv: Path):
        """Basic structural check: headings and tables."""
        report = generate_report(saved_files_with_graph_csv)
        assert report.count("#") >= 3  # at least a few headings
        assert "|" in report  # at least one table
