#!/usr/bin/env python3
"""Generate a comprehensive HTML analysis report.

Combines data from three sources into a single standalone HTML file:

1. **Vision CSV** (``graph_analysis_results.csv``) -- structured graph
   metadata extracted by the Claude vision model.
2. **Pipeline CSV exports** (``Significant_LF_Metrics.csv``,
   ``FDR_Sig_Global.csv``) -- significance tables from MATLAB.
3. **Log file parsing** -- structured metrics regex-extracted from MATLAB
   diary logs by :mod:`parse_log_metrics`.
4. **MAT file parsing** (optional) -- core-method comparison matrices and
   dosimetry summaries from :mod:`parse_mat_metrics`.

The report is written as ``analysis_report.html`` in the output folder and
includes a sticky navigation bar, stat cards, colour-coded significance
tables, cross-DWI trend comparisons, and a full appendix of every analysed
graph.

Usage:
    python generate_report.py [saved_files_path]
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

import markdown  # type: ignore
from tqdm import tqdm  # type: ignore

from shared import (  # type: ignore
    DWI_TYPES,
    group_by_graph_name,
    load_graph_csv,
    resolve_folder,
    setup_utf8_stdout,
)
from parse_csv_results import parse_all_csvs  # type: ignore
from parse_log_metrics import parse_all_logs  # type: ignore

# Re-export formatting helpers for backward compatibility (tests import these
# from generate_report).
from report_formatters import (  # noqa: F401  # type: ignore
    CSS,
    HTML_TEMPLATE,
    NAV_SECTIONS,
    REFERENCES,
    REPORT_JS,
    _cite,
    _copy_button,
    _dwi_badge,
    _effect_size_class,
    _effect_size_label,
    _esc,
    _figure_caption,
    _forest_plot_cell,
    _get_consensus,
    _h2,
    _manuscript_sentence,
    _nav_bar,
    _references_section,
    _section,
    _sig_class,
    _sig_tag,
    _stat_card,
    _table_caption,
    _trend_tag,
    get_numbering,
    reset_numbering,
)

# Re-export section builders for backward compatibility.
from report_sections import (  # noqa: F401  # type: ignore
    _part_break,
    _section_cover_page,
    _section_print_toc,
    _section_appendix,
    _section_broad_statistical_overview,
    _section_cohort_overview,
    _section_conclusions,
    _section_correlations,
    _section_cross_dwi_comparison,
    _section_data_availability,
    _section_data_completeness,
    _section_effect_sizes,
    _section_executive_summary,
    _section_feature_overlap,
    _section_figure_gallery,
    _section_figure_index,
    _section_graph_issues,
    _section_graph_overview,
    _section_hypothesis,
    _section_journal_guide,
    _section_limitations,
    _section_manuscript_ready_findings,
    _section_mat_data,
    _section_methods,
    _section_model_diagnostics,
    _section_multiple_comparisons,
    _section_patient_flow,
    _section_power_analysis,
    _section_predictive_performance,
    _section_publication_header,
    _section_reporting_checklist,
    _section_results_draft,
    _section_sensitivity_analysis,
    _section_stats_by_graph_type,
    _section_statistical_significance,
    _section_table_index,
    _section_treatment_response,
)

setup_utf8_stdout()


def generate_report(folder: Path) -> str:
    """Build the full HTML report string from all available data sources.

    The function loads data from CSV exports, log files, MAT-file JSON,
    and vision analysis CSV (if available), then delegates to section
    builder functions in :mod:`report_sections` to produce each part of
    the report.

    Parameters
    ----------
    folder : Path
        Path to the ``saved_files_*`` output folder.

    Returns
    -------
    str
        Complete HTML document as a string (ready to write to disk).
    """
    # Extract the timestamp suffix from the folder name for display.
    timestamp = folder.name.replace("saved_files_", "")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Load pipeline CSV exports (significance tables) ──
    try:
        csv_data = parse_all_csvs(folder)
    except Exception:
        csv_data = None

    # ── Load parsed log metrics ──
    try:
        log_data = parse_all_logs(folder)
    except Exception:
        log_data = None

    # ── Load MAT metrics JSON (generated by parse_mat_metrics.py) ──
    mat_data = {}
    for dt in DWI_TYPES:
        mat_path = folder / f"parsed_mat_metrics_{dt}.json"
        if mat_path.exists():
            try:
                with open(mat_path, "r", encoding="utf-8") as f:
                    mat_data[dt] = json.load(f)
            except Exception as e:
                print(f"Error loading {mat_path.name}: {e}")

    # ── Load vision CSV (graph_analysis_results.csv) ──
    rows = load_graph_csv(folder)
    # Group rows by normalised graph name for cross-DWI comparison.
    groups = group_by_graph_name(rows) if rows else {}

    # ── Detect which DWI types are present in this run ──
    dwi_types_present = []
    if log_data is not None:
        for d in DWI_TYPES:
            if d in log_data:  # type: ignore
                dwi_types_present.append(d)
    # Fallback: check for DWI-type subdirectories on disk.
    if not dwi_types_present:
        dwi_types_present = [d for d in DWI_TYPES if (folder / d).is_dir()]

    # Reset table/figure numbering for this report.
    reset_numbering()

    # Section builders to call (name for progress display, callable, args).
    # We build this list and iterate with a progress bar.
    section_steps: list[tuple[str, object, tuple]] = []

    h = []  # Accumulator for HTML chunks (joined at the end).
    h.append("<!DOCTYPE html>")
    h.append('<html lang="en">')
    h.append("<head>")
    h.append('<meta charset="utf-8">')
    h.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    h.append(f"<title>Analysis Report \u2014 {_esc(timestamp)}</title>")
    h.append(f"<style>{CSS}</style>")
    h.append(f"<script>{REPORT_JS}</script>")
    h.append("</head>")
    h.append("<body>")

    # ── Cover page (print-only; hidden on screen) ──
    h.extend(_section_cover_page(timestamp, dwi_types_present, len(rows) if rows else 0))

    # ── Sticky navigation bar (anchors to each report section) ──
    h.append(_nav_bar())

    # ── Report header with metadata ──
    h.append(f"<h1>Analysis Report \u2014 {_esc(timestamp)}</h1>")
    h.append('<div class="meta">')
    h.append(f"<span><strong>Generated:</strong> {now}</span>")
    h.append(f"<span><strong>DWI types:</strong> {', '.join(dwi_types_present) or 'None detected'}</span>")
    if rows:
        h.append(f"<span><strong>Graphs analysed:</strong> {len(rows)}</span>")
    h.append("</div>")

    # ── Table of contents (screen + PDF) ──
    h.extend(_section_print_toc())

    # ── Part 1: Overview ──
    h.append(_part_break("Part 1 — Overview"))

    # Build a list of (section_name, builder_fn, args) for progress tracking.
    section_steps = [
        ("Executive summary", _section_executive_summary, (log_data, dwi_types_present, rows, csv_data, timestamp, mat_data)),
        ("Methods", _section_methods, (dwi_types_present, mat_data, log_data)),
        ("Cohort overview", _section_cohort_overview, (mat_data, log_data, dwi_types_present)),
        ("Patient flow", _section_patient_flow, (log_data, dwi_types_present, mat_data)),
    ]

    report_bar = tqdm(
        total=20,  # approximate total sections
        desc="Building report",
        unit="section",
        bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} sections [{elapsed}<{remaining}] {postfix}",
    )

    for name, fn, fn_args in section_steps:
        report_bar.set_postfix_str(name, refresh=True)
        h.extend(fn(*fn_args))  # type: ignore
        report_bar.update(1)

    # ── Part 2: Data ──
    h.append(_part_break("Part 2 — Data"))

    # ── Data Quality ──
    report_bar.set_postfix_str("Data quality", refresh=True)
    h.append(_h2("Data Quality", "data-quality"))
    has_quality_data = False

    if log_data:
        for dwi_type in dwi_types_present:
            if dwi_type not in log_data:
                continue
            bl = log_data[dwi_type].get("baseline", {})
            outlier_flags = bl.get("outlier_flags", [])
            total_out = bl.get("total_outliers")
            baseline_exc = bl.get("baseline_exclusion")

            if not outlier_flags and not total_out and not baseline_exc:
                continue

            has_quality_data = True
            h.append(f"<h3>{_dwi_badge(dwi_type)} Baseline Quality</h3>")

            # Summary stats row
            qcards = []
            if total_out:
                pct = total_out.get("pct", 0)
                qcards.append(_stat_card(
                    "Outliers Removed",
                    f"{total_out['n_removed']}/{total_out['n_total']}",
                    f"{pct:.1f}% of samples"
                ))
            if baseline_exc:
                qcards.append(_stat_card(
                    "Baseline Excluded",
                    f"{baseline_exc['n_excluded']}/{baseline_exc['n_total']}",
                    "missing baseline data"
                ))
                lf_inc = baseline_exc.get("lf_rate_included")
                lf_exc = baseline_exc.get("lf_rate_excluded")
                if lf_inc is not None and lf_exc is not None:
                    qcards.append(_stat_card(
                        "LF Rate",
                        f"{lf_inc:.1f}% / {lf_exc:.1f}%",
                        "included / excluded"
                    ))
            if qcards:
                h.append('<div class="stat-grid">')
                h.extend(qcards)
                h.append("</div>")

            # Per-metric outlier flags table with balance assessment
            if outlier_flags:
                h.append("<h4>Per-Metric Outlier Flags</h4>")
                h.append('<p class="meta">Disproportionate removal from one outcome group '
                         'may bias downstream analyses.</p>')
                h.append("<table><thead><tr>"
                         "<th>Metric</th><th>Flagged</th>"
                         "<th>Local Failure</th><th>Local Control</th><th>Competing Risk</th>"
                         "<th>Balance</th>"
                         "</tr></thead><tbody>")
                for o in outlier_flags:
                    n_total = o['n_flagged']
                    n_lf = o['n_lf']
                    n_lc = o['n_lc']
                    n_cr = o['n_cr']
                    if n_total > 0:
                        max_grp = max(n_lf, n_lc, n_cr)
                        if max_grp / n_total > 0.7 and n_total >= 3:
                            balance = '<span class="differ">Imbalanced</span>'
                        else:
                            balance = '<span class="agree">Balanced</span>'
                    else:
                        balance = "\u2014"
                    h.append(
                        f"<tr><td><code>{_esc(o['metric'])}</code></td>"
                        f"<td><strong>{n_total}</strong></td>"
                        f"<td>{n_lf}</td><td>{n_lc}</td><td>{n_cr}</td>"
                        f"<td>{balance}</td></tr>"
                    )
                h.append("</tbody></table>")

            # Warn if baseline exclusion creates selection bias
            if baseline_exc:
                lf_inc = baseline_exc.get("lf_rate_included")
                lf_exc = baseline_exc.get("lf_rate_excluded")
                if lf_inc is not None and lf_exc is not None:
                    diff = abs(lf_exc - lf_inc)
                    if diff > 15:
                        h.append(
                            f'<div class="warn-box">Baseline exclusion may introduce '
                            f'selection bias: LF rate among excluded patients '
                            f'({lf_exc:.1f}%) differs from included patients '
                            f'({lf_inc:.1f}%) by {diff:.1f} percentage points.</div>'
                        )

    if not has_quality_data:
        h.append('<p class="meta">No baseline quality data found in logs.</p>')
    report_bar.update(1)

    # Remaining sections with progress tracking.
    remaining_sections = [
        ("Data completeness", _section_data_completeness, (log_data, dwi_types_present)),
        ("Hypothesis", _section_hypothesis, (groups, log_data, mat_data)),
        ("Graph overview", _section_graph_overview, (rows,)),
        ("Graph issues", _section_graph_issues, (rows,)),
        ("Stats by graph type", _section_stats_by_graph_type, (rows,)),
        ("Statistical significance", _section_statistical_significance, (rows, csv_data, log_data, dwi_types_present)),
        ("Broad statistical overview", _section_broad_statistical_overview, (log_data, dwi_types_present)),
        ("Effect sizes", _section_effect_sizes, (log_data, dwi_types_present, csv_data)),
        ("Multiple comparisons", _section_multiple_comparisons, (log_data, dwi_types_present, csv_data)),
        ("Cross-DWI comparison", _section_cross_dwi_comparison, (groups, csv_data)),
    ]

    for name, fn, fn_args in remaining_sections:
        report_bar.set_postfix_str(name, refresh=True)
        h.extend(fn(*fn_args))
        report_bar.update(1)

    # ── 7. FDR Global ──
    report_bar.set_postfix_str("FDR global", refresh=True)
    if csv_data and csv_data.get("fdr_global"):
        fdr_global = csv_data["fdr_global"]
        if fdr_global:
            h.append(_h2("FDR Global Correction Results", "fdr-global"))
            h.append("<p><em>Metrics surviving Benjamini-Hochberg FDR correction across the full "
                     "feature set, as exported by the pipeline.</em></p>")
            for dwi_type in DWI_TYPES:
                if dwi_type not in fdr_global:
                    continue
                fdr_rows = fdr_global[dwi_type]
                if not fdr_rows:
                    continue
                h.append(f"<h3>{_dwi_badge(dwi_type)} \u2014 {len(fdr_rows)} tests</h3>")
                headers = list(fdr_rows[0].keys())[:10]  # type: ignore
                tbl_cls = ' class="table-wide"' if len(headers) > 6 else ""
                h.append(f"<table{tbl_cls}><thead><tr>")
                for hdr in headers:
                    h.append(f"<th>{_esc(hdr)}</th>")
                h.append("</tr></thead><tbody>")
                for fr in fdr_rows:
                    h.append("<tr>")
                    for hdr in headers:
                        val = str(fr.get(hdr, ""))  # type: ignore
                        # Highlight p-value columns
                        try:
                            fval = float(val)
                            if "p" in hdr.lower() and 0 < fval < 0.05:
                                cls = _sig_class(fval)
                                h.append(f'<td class="{cls}">{_esc(val[:40])}</td>')  # type: ignore
                                continue
                        except (ValueError, TypeError):
                            pass
                        h.append(f"<td>{_esc(val[:40])}</td>")  # type: ignore
                    h.append("</tr>")
                h.append("</tbody></table>")
    else:
        h.append(_h2("FDR Global Correction Results", "fdr-global"))
        h.append('<p class="meta">No FDR_Sig_Global.csv files found.</p>')
    report_bar.update(1)

    final_sections = [
        ("Correlations", _section_correlations, (rows,)),
        ("Treatment response", _section_treatment_response, (groups,)),
        ("Predictive performance", _section_predictive_performance, (log_data, dwi_types_present)),
        ("Feature overlap", _section_feature_overlap, (log_data, dwi_types_present)),
        ("Model diagnostics", _section_model_diagnostics, (log_data, dwi_types_present, mat_data)),
        ("Power analysis", _section_power_analysis, (log_data, dwi_types_present, mat_data)),
        ("Sensitivity analysis", _section_sensitivity_analysis, (log_data, dwi_types_present, mat_data)),
        ("MAT data", _section_mat_data, (mat_data,)),
        ("Limitations", _section_limitations, (log_data, dwi_types_present, mat_data)),
        ("Conclusions", _section_conclusions, (log_data, dwi_types_present, csv_data, mat_data, groups)),
        ("Reporting checklist", _section_reporting_checklist, (log_data, dwi_types_present, mat_data, csv_data, rows)),
        ("Table index", _section_table_index, ()),
        ("Figure index", _section_figure_index, ()),
        ("Results draft", _section_results_draft, (log_data, dwi_types_present, csv_data, mat_data, groups)),
        ("Figure gallery", _section_figure_gallery, (folder, rows)),
        ("Journal guide", _section_journal_guide, (log_data, dwi_types_present, mat_data)),
        ("Data availability", _section_data_availability, ()),
        ("References", _references_section, ()),
        ("Appendix", _section_appendix, (rows,)),
    ]

    # Update total to reflect actual section count.
    report_bar.total = report_bar.n + len(final_sections)
    report_bar.refresh()

    for name, fn, fn_args in final_sections:
        report_bar.set_postfix_str(name, refresh=True)
        h.extend(fn(*fn_args))
        report_bar.update(1)

    report_bar.set_postfix_str("complete", refresh=True)
    report_bar.close()

    # Footer
    h.append(f"<footer>Report generated by pancData3 analysis suite on {now}</footer>")
    h.append("</body>")
    h.append("</html>")

    return "\n".join(h)


def markdown_to_html(md_text: str, title: str) -> str:
    """Convert Markdown text to a styled standalone HTML document.

    Uses the ``python-markdown`` library with table, fenced-code, and
    table-of-contents extensions.  The result is wrapped in the
    :data:`report_formatters.HTML_TEMPLATE` for consistent styling.

    Parameters
    ----------
    md_text : str
        Raw Markdown content.
    title : str
        HTML ``<title>`` for the document.

    Returns
    -------
    str
        Complete HTML document string.
    """
    body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc"],
    )
    return HTML_TEMPLATE.format(title=title, body=body)


def _html_to_pdf_weasyprint(html_content: str, pdf_path: Path) -> bool:
    """Attempt PDF generation via WeasyPrint. Returns True on success."""
    try:
        from weasyprint import HTML as WeasyprintHTML  # type: ignore[import-untyped]
        WeasyprintHTML(string=html_content).write_pdf(str(pdf_path))
        return True
    except ImportError:
        print("  WeasyPrint not installed (pip install weasyprint).")
        return False
    except OSError as e:
        # WeasyPrint is installed but its native GTK/Pango libraries are missing.
        # On Windows this requires installing the GTK3 runtime separately.
        print(f"  WeasyPrint native library error: {e}")
        if sys.platform == "win32":
            print("  On Windows, WeasyPrint requires the GTK3 runtime.")
            print("  Install it from: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer")
        return False
    except Exception as e:
        print(f"  WeasyPrint failed: {e}")
        return False


def _html_to_pdf_browser(html_content: str, pdf_path: Path) -> bool:
    """Attempt PDF generation via a headless Chrome/Edge/Chromium subprocess.

    Writes the HTML to a temporary file, invokes a headless browser with
    ``--print-to-pdf``, and cleans up the temp file afterwards.

    Returns True on success.
    """
    import subprocess
    import tempfile

    # Candidate browser executables to try, in order of preference.
    candidates: list[str] = []
    if sys.platform == "win32":
        import os
        # Common Chrome/Edge install paths on Windows.
        win_paths = [
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
            os.path.expanduser(r"~\AppData\Local\Google\Chrome\Application\chrome.exe"),
            r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        ]
        candidates = [p for p in win_paths if Path(p).exists()]
        # Also try commands on PATH.
        candidates += ["chrome", "msedge", "chromium"]
    elif sys.platform == "darwin":
        candidates = [
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "/Applications/Chromium.app/Contents/MacOS/Chromium",
            "google-chrome",
            "chromium",
        ]
    else:
        candidates = ["google-chrome", "chromium-browser", "chromium", "google-chrome-stable"]

    if not candidates:
        return False

    # Write HTML to a temporary file so the browser can load it via file://.
    tmp = tempfile.NamedTemporaryFile(
        suffix=".html", delete=False, mode="w", encoding="utf-8"
    )
    try:
        tmp.write(html_content)
        tmp.close()
        tmp_path = Path(tmp.name)

        # file:// URI — use forward slashes even on Windows.
        file_uri = "file:///" + tmp_path.as_posix().lstrip("/")

        for browser in candidates:
            try:
                result = subprocess.run(
                    [
                        browser,
                        "--headless",
                        "--disable-gpu",
                        "--no-sandbox",
                        f"--print-to-pdf={pdf_path}",
                        "--print-to-pdf-no-header",
                        file_uri,
                    ],
                    capture_output=True,
                    text=True,
                    timeout=120,
                )
                if result.returncode == 0 and pdf_path.exists() and pdf_path.stat().st_size > 0:
                    print(f"  Browser PDF engine: {browser}")
                    return True
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
            except Exception:
                continue
    finally:
        try:
            Path(tmp.name).unlink(missing_ok=True)
        except Exception:
            pass

    return False


def html_to_pdf(html_content: str, pdf_path: Path) -> bool:
    """Convert an HTML report string to a PDF file.

    Tries WeasyPrint first; if that fails (e.g. missing GTK libraries on
    Windows), falls back to a headless Chrome/Edge/Chromium subprocess.

    Parameters
    ----------
    html_content : str
        Complete HTML document string.
    pdf_path : Path
        Output path for the PDF file.

    Returns
    -------
    bool
        True if PDF generation succeeded, False otherwise.
    """
    # Try WeasyPrint (best quality, but requires GTK native libs on Windows).
    print("  Trying WeasyPrint ...")
    if _html_to_pdf_weasyprint(html_content, pdf_path):
        return True

    # Fallback: headless Chrome/Edge/Chromium (no extra Python packages needed).
    print("  Trying headless browser fallback ...")
    if _html_to_pdf_browser(html_content, pdf_path):
        return True

    print("  PDF generation failed. To enable PDF output, either:")
    print("    1. Install GTK3 runtime for WeasyPrint (Windows):")
    print("       https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer")
    print("    2. Install Google Chrome or Microsoft Edge.")
    print("  The HTML report is still available.")
    return False


def main():
    """CLI entry point: generate the HTML report and write it to disk."""
    folder = resolve_folder(sys.argv)

    skip_pdf = "--no-pdf" in sys.argv
    skip_html = "--no-html" in sys.argv

    html_report = generate_report(folder)

    out_path = folder / "analysis_report.html"
    if not skip_html:
        out_path.write_text(html_report, encoding="utf-8")
        print(f"Report written to: {out_path}")
        print(f"  Length: {len(html_report)} characters")

    # Generate PDF version
    if not skip_pdf:
        pdf_path = folder / "analysis_report.pdf"
        print(f"Generating PDF: {pdf_path}")
        if html_to_pdf(html_report, pdf_path):
            print(f"  PDF written: {pdf_path}")
            print(f"  Size: {pdf_path.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
