#!/usr/bin/env python3
"""Generate a comprehensive HTML analysis report.

Combines data from three sources into a single standalone HTML file:

1. **Vision CSV** (``graph_analysis_results.csv``) -- structured graph
   metadata extracted by the Claude vision model.
2. **Pipeline CSV exports** (``Significant_LF_Metrics.csv``,
   ``FDR_Sig_Global.csv``) -- significance tables from MATLAB.
3. **Log file parsing** -- structured metrics regex-extracted from MATLAB
   diary logs by :mod:`parse_log_metrics`.
4. **MAT file parsing** (optional) -- core-method comparison matrices and
   dosimetry summaries from :mod:`parse_mat_metrics`.

The report is written as ``analysis_report.html`` in the output folder and
includes a sticky navigation bar, stat cards, colour-coded significance
tables, cross-DWI trend comparisons, and a full appendix of every analysed
graph.

Usage:
    python generate_report.py [saved_files_path]
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

import markdown

from shared import (
    DWI_TYPES,
    group_by_graph_name,
    load_graph_csv,
    resolve_folder,
    setup_utf8_stdout,
)
from parse_csv_results import parse_all_csvs
from parse_log_metrics import parse_all_logs

# Re-export formatting helpers for backward compatibility (tests import these
# from generate_report).
from report_formatters import (  # noqa: F401
    CSS,
    HTML_TEMPLATE,
    NAV_SECTIONS,
    REFERENCES,
    _cite,
    _dwi_badge,
    _effect_size_class,
    _effect_size_label,
    _esc,
    _forest_plot_cell,
    _get_consensus,
    _h2,
    _nav_bar,
    _references_section,
    _section,
    _sig_class,
    _sig_tag,
    _stat_card,
    _table_caption,
    _trend_tag,
    reset_numbering,
)

# Re-export section builders for backward compatibility.
from report_sections import (  # noqa: F401
    _section_appendix,
    _section_cohort_overview,
    _section_conclusions,
    _section_correlations,
    _section_cross_dwi_comparison,
    _section_data_availability,
    _section_effect_sizes,
    _section_executive_summary,
    _section_graph_issues,
    _section_graph_overview,
    _section_hypothesis,
    _section_limitations,
    _section_mat_data,
    _section_methods,
    _section_model_diagnostics,
    _section_multiple_comparisons,
    _section_predictive_performance,
    _section_publication_header,
    _section_stats_by_graph_type,
    _section_statistical_significance,
    _section_treatment_response,
)

setup_utf8_stdout()


def generate_report(folder: Path) -> str:
    """Build the full HTML report string from all available data sources.

    The function loads data from CSV exports, log files, MAT-file JSON,
    and vision analysis CSV (if available), then delegates to section
    builder functions in :mod:`report_sections` to produce each part of
    the report.

    Parameters
    ----------
    folder : Path
        Path to the ``saved_files_*`` output folder.

    Returns
    -------
    str
        Complete HTML document as a string (ready to write to disk).
    """
    # Extract the timestamp suffix from the folder name for display.
    timestamp = folder.name.replace("saved_files_", "")
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── Load pipeline CSV exports (significance tables) ──
    try:
        csv_data = parse_all_csvs(folder)
    except Exception:
        csv_data = None

    # ── Load parsed log metrics ──
    try:
        log_data = parse_all_logs(folder)
    except Exception:
        log_data = None

    # ── Load MAT metrics JSON (generated by parse_mat_metrics.py) ──
    mat_data = {}
    for dt in DWI_TYPES:
        mat_path = folder / f"parsed_mat_metrics_{dt}.json"
        if mat_path.exists():
            try:
                with open(mat_path, "r", encoding="utf-8") as f:
                    mat_data[dt] = json.load(f)
            except Exception as e:
                print(f"Error loading {mat_path.name}: {e}")

    # ── Load vision CSV (graph_analysis_results.csv) ──
    rows = load_graph_csv(folder)
    # Group rows by normalised graph name for cross-DWI comparison.
    groups = group_by_graph_name(rows) if rows else {}

    # ── Detect which DWI types are present in this run ──
    dwi_types_present = []
    if log_data is not None:
        for d in DWI_TYPES:
            if d in log_data:
                dwi_types_present.append(d)
    # Fallback: check for DWI-type subdirectories on disk.
    if not dwi_types_present:
        dwi_types_present = [d for d in DWI_TYPES if (folder / d).is_dir()]

    # Reset table/figure numbering for this report.
    reset_numbering()

    h = []  # Accumulator for HTML chunks (joined at the end).
    h.append("<!DOCTYPE html>")
    h.append('<html lang="en">')
    h.append("<head>")
    h.append('<meta charset="utf-8">')
    h.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    h.append(f"<title>Analysis Report \u2014 {_esc(timestamp)}</title>")
    h.append(f"<style>{CSS}</style>")
    h.append("</head>")
    h.append("<body>")

    # ── Sticky navigation bar (anchors to each report section) ──
    h.append(_nav_bar())

    # ── Report header with metadata ──
    h.append(f"<h1>Analysis Report \u2014 {_esc(timestamp)}</h1>")
    h.append('<div class="meta">')
    h.append(f"<span><strong>Generated:</strong> {now}</span>")
    h.append(f"<span><strong>DWI types:</strong> {', '.join(dwi_types_present) or 'None detected'}</span>")
    if rows:
        h.append(f"<span><strong>Graphs analysed:</strong> {len(rows)}</span>")
    h.append("</div>")

    # ── Publication metadata (author/institution placeholders) ──
    h.extend(_section_publication_header())

    h.extend(_section_executive_summary(log_data, dwi_types_present, rows, csv_data, timestamp, mat_data))

    h.extend(_section_methods(dwi_types_present, mat_data, log_data))

    h.extend(_section_cohort_overview(mat_data, log_data, dwi_types_present))

    # ── 2. Data Quality ──
    h.append(_h2("Data Quality", "data-quality"))
    has_quality_data = False

    if log_data:
        for dwi_type in dwi_types_present:
            if dwi_type not in log_data:
                continue
            bl = log_data[dwi_type].get("baseline", {})
            outlier_flags = bl.get("outlier_flags", [])
            total_out = bl.get("total_outliers")
            baseline_exc = bl.get("baseline_exclusion")

            if not outlier_flags and not total_out and not baseline_exc:
                continue

            has_quality_data = True
            h.append(f"<h3>{_dwi_badge(dwi_type)} Baseline Quality</h3>")

            # Summary stats row
            qcards = []
            if total_out:
                pct = total_out.get("pct", 0)
                qcards.append(_stat_card(
                    "Outliers Removed",
                    f"{total_out['n_removed']}/{total_out['n_total']}",
                    f"{pct:.1f}% of samples"
                ))
            if baseline_exc:
                qcards.append(_stat_card(
                    "Baseline Excluded",
                    f"{baseline_exc['n_excluded']}/{baseline_exc['n_total']}",
                    "missing baseline data"
                ))
                lf_inc = baseline_exc.get("lf_rate_included")
                lf_exc = baseline_exc.get("lf_rate_excluded")
                if lf_inc is not None and lf_exc is not None:
                    qcards.append(_stat_card(
                        "LF Rate",
                        f"{lf_inc:.1f}% / {lf_exc:.1f}%",
                        "included / excluded"
                    ))
            if qcards:
                h.append('<div class="stat-grid">')
                h.extend(qcards)
                h.append("</div>")

            # Per-metric outlier flags table
            if outlier_flags:
                h.append("<h4>Per-Metric Outlier Flags</h4>")
                h.append("<table><thead><tr>"
                         "<th>Metric</th><th>Flagged</th>"
                         "<th>Local Failure</th><th>Local Control</th><th>Competing Risk</th>"
                         "</tr></thead><tbody>")
                for o in outlier_flags:
                    h.append(
                        f"<tr><td><code>{_esc(o['metric'])}</code></td>"
                        f"<td><strong>{o['n_flagged']}</strong></td>"
                        f"<td>{o['n_lf']}</td><td>{o['n_lc']}</td><td>{o['n_cr']}</td></tr>"
                    )
                h.append("</tbody></table>")

    if not has_quality_data:
        h.append('<p class="meta">No baseline quality data found in logs.</p>')

    h.extend(_section_hypothesis(groups, log_data, mat_data))
    h.extend(_section_graph_overview(rows))
    h.extend(_section_graph_issues(rows))
    h.extend(_section_stats_by_graph_type(rows))
    h.extend(_section_statistical_significance(rows, csv_data, log_data, dwi_types_present))
    h.extend(_section_effect_sizes(log_data, dwi_types_present, csv_data))
    h.extend(_section_multiple_comparisons(log_data, dwi_types_present, csv_data))
    h.extend(_section_cross_dwi_comparison(groups, csv_data))

    # ── 7. FDR Global ──
    if csv_data and csv_data.get("fdr_global"):
        fdr_global = csv_data["fdr_global"]
        if fdr_global:
            h.append(_h2("FDR Global Correction Results", "fdr-global"))
            h.append("<p><em>Metrics surviving Benjamini-Hochberg FDR correction across the full "
                     "feature set, as exported by the pipeline.</em></p>")
            for dwi_type in DWI_TYPES:
                if dwi_type not in fdr_global:
                    continue
                fdr_rows = fdr_global[dwi_type]
                if not fdr_rows:
                    continue
                h.append(f"<h3>{_dwi_badge(dwi_type)} \u2014 {len(fdr_rows)} tests</h3>")
                headers = list(fdr_rows[0].keys())[:10]
                h.append("<table><thead><tr>")
                for hdr in headers:
                    h.append(f"<th>{_esc(hdr)}</th>")
                h.append("</tr></thead><tbody>")
                for fr in fdr_rows:
                    h.append("<tr>")
                    for hdr in headers:
                        val = str(fr.get(hdr, ""))
                        # Highlight p-value columns
                        try:
                            fval = float(val)
                            if "p" in hdr.lower() and 0 < fval < 0.05:
                                cls = _sig_class(fval)
                                h.append(f'<td class="{cls}">{_esc(val[:40])}</td>')
                                continue
                        except (ValueError, TypeError):
                            pass
                        h.append(f"<td>{_esc(val[:40])}</td>")
                    h.append("</tr>")
                h.append("</tbody></table>")
    else:
        h.append(_h2("FDR Global Correction Results", "fdr-global"))
        h.append('<p class="meta">No FDR_Sig_Global.csv files found.</p>')

    h.extend(_section_correlations(rows))
    h.extend(_section_treatment_response(groups))
    h.extend(_section_predictive_performance(log_data, dwi_types_present))
    h.extend(_section_model_diagnostics(log_data, dwi_types_present, mat_data))
    h.extend(_section_mat_data(mat_data))
    h.extend(_section_limitations(log_data, dwi_types_present, mat_data))
    h.extend(_section_conclusions(log_data, dwi_types_present, csv_data, mat_data, groups))
    h.extend(_section_data_availability())
    h.extend(_references_section())
    h.extend(_section_appendix(rows))

    # Footer
    h.append(f"<footer>Report generated by pancData3 analysis suite on {now}</footer>")
    h.append("</body>")
    h.append("</html>")

    return "\n".join(h)


def markdown_to_html(md_text: str, title: str) -> str:
    """Convert Markdown text to a styled standalone HTML document.

    Uses the ``python-markdown`` library with table, fenced-code, and
    table-of-contents extensions.  The result is wrapped in the
    :data:`report_formatters.HTML_TEMPLATE` for consistent styling.

    Parameters
    ----------
    md_text : str
        Raw Markdown content.
    title : str
        HTML ``<title>`` for the document.

    Returns
    -------
    str
        Complete HTML document string.
    """
    body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc"],
    )
    return HTML_TEMPLATE.format(title=title, body=body)


def html_to_pdf(html_content: str, pdf_path: Path) -> bool:
    """Convert an HTML report string to a PDF file using WeasyPrint.

    Parameters
    ----------
    html_content : str
        Complete HTML document string.
    pdf_path : Path
        Output path for the PDF file.

    Returns
    -------
    bool
        True if PDF generation succeeded, False otherwise.
    """
    try:
        from weasyprint import HTML as WeasyprintHTML  # type: ignore[import-untyped]
        WeasyprintHTML(string=html_content).write_pdf(str(pdf_path))
        return True
    except ImportError:
        print("  WeasyPrint not installed. Install with: pip install weasyprint")
        print("  Skipping PDF generation; HTML report is still available.")
        return False
    except Exception as e:
        print(f"  PDF generation failed: {e}")
        print("  HTML report is still available.")
        return False


def main():
    """CLI entry point: generate the HTML report and write it to disk."""
    folder = resolve_folder(sys.argv)

    skip_pdf = "--no-pdf" in sys.argv
    skip_html = "--no-html" in sys.argv

    html_report = generate_report(folder)

    out_path = folder / "analysis_report.html"
    if not skip_html:
        out_path.write_text(html_report, encoding="utf-8")
        print(f"Report written to: {out_path}")
        print(f"  Length: {len(html_report)} characters")

    # Generate PDF version
    if not skip_pdf:
        pdf_path = folder / "analysis_report.pdf"
        print(f"Generating PDF: {pdf_path}")
        if html_to_pdf(html_report, pdf_path):
            print(f"  PDF written: {pdf_path}")
            print(f"  Size: {pdf_path.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
